---
department:
  name: environmental_health_and_safety
  display_name: Environmental Health & Safety
  description: Consolidated department combining Animal Control, Public Health. Both
    departments handle animal-related emergencies, shared responsibilities in managing
    zoonotic threats
  invariants:
  - serve citizens efficiently
  - respond to emergencies promptly
  - maintain operational readiness
capabilities:
- Assess and handle threats posed by dangerous animals
- Capture and contain aggressive stray dogs
- Centralized coordination with law enforcement
- Coordinate with law enforcement and public safety agencies
- Coordinating with animal control and emergency services to handle dangerous animals
  and rabid wildlife
- Implementing public safety advisories and control measures for disease vectors
- Integrated disease vector management protocols
- Managing zoonotic disease threats, such as rabies outbreaks
- Provide emergency response for animal-related threats
- Responding to public health emergencies
- Unified emergency response for all animal-related incidents
message_types:
  subscribes_to:
  - emergency_911_message
  - health_check_message
  publishes:
  - animal_sighting
  - dangerous_animal_report
  - dangerous_animal_response
  - dog_attack
  - public_health_alert
  - public_safety_alert
  - zoonotic_disease_entry
routing_rules:
  emergency_911_message:
  - condition: message contains relevant keywords
    keywords:
    - responsible
    - protecting
    - promoting
    - public
    - health
    priority: high
  health_check_message:
  - condition: always
    priority: normal
message_actions:
  emergency_911_message: handle_emergency
  health_check_message: respond_health_check
  dog_attack: handle_dog_attack
  animal_sighting: handle_animal_sighting
  dangerous_animal_response: handle_dangerous_animal_response
  public_safety_alert: handle_public_safety_alert
  public_health_alert: handle_public_health_alert
  dangerous_animal_report: handle_dangerous_animal_report
  zoonotic_disease_entry: handle_zoonotic_disease_entry
action_configs:
  handle_emergency:
    response_template: "\U0001F6A8 PUBLIC_HEALTH_DEPARTMENT: Responding to {{emergency_type}}
      at {{location}}"
    additional_actions:
    - log_emergency
    - notify_dispatch
    publish_response: true
  respond_health_check:
    response_template: "\U0001F497 public_health_department is operational"
    publish_response: true
ai_analysis:
  enabled: false
  context: You are the environmental_health_and_safety department. Handle consolidated
    department combining animal control, public health. both departments handle animal-related
    emergencies, shared responsibilities in managing zoonotic threats.
logging:
  level: info
  statistics_interval: 300
consolidation_info:
  merged_from:
  - Animal Control
  - Public Health
  reason: Both departments handle animal-related emergencies, shared responsibilities
    in managing zoonotic threats
  created_at: '2025-08-26T16:41:35-05:00'
