---
department:
  name: environmental_services_department
  display_name: Environmental Services
  description: Handles the management, containment, and cleanup of environmental hazards
    such as toxic waste spills to protect public health and the environment.
  invariants:
  - serve citizens efficiently
  - respond to emergencies promptly
  - maintain operational readiness
capabilities:
- Respond to reports of hazardous waste spills
- Contain and clean up toxic substances
- Assess environmental impact and coordinate with other agencies
- Ensure public safety and prevent contamination of water sources
message_types:
  subscribes_to:
  - health_check_message
  - emergency_911_message
  publishes:
  - toxic_waste_spill
  - environmental_hazard_report
  - water_contamination_alert
routing_rules:
  emergency_911_message:
  - condition: message contains relevant keywords
    keywords:
    - handles
    - management
    - containment
    - cleanup
    - environmental
    priority: high
  health_check_message:
  - condition: always
    priority: normal
message_actions:
  emergency_911_message: handle_emergency
  health_check_message: respond_health_check
  toxic_waste_spill: handle_toxic_waste_spill
  environmental_hazard_report: handle_environmental_hazard_report
  water_contamination_alert: handle_water_contamination_alert
action_configs:
  handle_emergency:
    response_template: "\U0001F6A8 ENVIRONMENTAL_SERVICES: Responding to {{emergency_type}}
      at {{location}}"
    additional_actions:
    - log_emergency
    - notify_dispatch
    publish_response: true
  respond_health_check:
    response_template: "\U0001F497 environmental_services is operational"
    publish_response: true
ai_analysis:
  enabled: false
  context: You are the environmental_services department. Handle handles the management,
    containment, and cleanup of environmental hazards such as toxic waste spills to
    protect public health and the environment..
logging:
  level: info
  statistics_interval: 300
